# Seção de hosts IP ou nomes de máquinas no sistema
hosts:
  camera: "192.168.0.20"   # IP do servidor/câmera
  database: "localhost"    # IP ou hostname do banco de dados

# Seção de portas utilizadas pelos serviços
ports:
  camera: 80               # Porta HTTP da câmera
  database: 3306           # Porta padrão do MySQL/MariaDB

# Credenciais de acesso aos serviços
credentials:
  database:
    user: "root"           # Usuário do banco de dados (mesma do docker-compose)
    password: "@Isac1998"  # Senha do banco de dados (mesma do docker-compose)
    name: "debug"          # Nome do banco de dados a ser usado (mesmo do docker-compose)

# Detalhes adicionais sobre o banco de dados
details:
  database:
    tables:
      perfis: "usuarios"         # Nome da tabela de perfis/usuários
      historico: "historico"   # Nome da tabela de histórico de acessos
      dispositivos: "dispositivos" # Nome da tabela de dispositivos
