hosts:
  camera: "192.168.0.20"
  database: "localhost"

ports:
  camera: 80
  database: 3306

credentials:
  database:
    user: "root"
    password: "@Isac1998"
    name: "debug"

details:
  database:
    tables:
      perfis:
        name: "usuarios"
        columns:
          password: "senha"
          encoding: "encodings"
          others:
            - "id"
            - "alias"
            - "email"
            - "icon_path"
            - "permission_level"
          
      historico: "historico"
      dispositivos: "dispositivos"
    
