hosts:
  camera: "192.168.0.20"
  database: "localhost"

ports:
  camera: 80
  database: 3306

credentials:
  database:
    user: "root"
    password: "@Isac1998"
    name: "debug"

details:
  database:
    tables:
      perfis: "usuarios"
      historico: "historico"
      dispositivos: "dispositivos"
    
    columns:
      perfis:
        nome: "nome"
        