# -----------------------------
# Arquivo Docker Compose para levantar um ambiente de desenvolvimento com MySQL e Adminer
# -----------------------------

services:

  db:
    # Serviço do banco de dados MySQL
    image: mysql # Imagem oficial do MySQL no Docker Hub
    container_name: <Nome para o Container do seu DB> # Nome do container (facilita referência)
    environment:
      # Variáveis de ambiente para configurar o MySQL
      - MYSQL_ROOT_PASSWORD=<a senha do root do MySQL> # Senha do usuário root do MySQL
      - MYSQL_DATABASE=<a nome do banco de dados> # Banco de dados inicial que será criado automaticamente
    ports:
      - "<a porta host>:3306" # Mapeia a porta padrão do MySQL do container (3306) para a máquina host
    volumes:
      - ./core/db:/docker-entrypoint-initdb.d
        # Mapeia scripts SQL ou arquivos de inicialização da pasta local ./core/db para o container
        # Qualquer script .sql dentro dessa pasta será executado na inicialização do MySQL
    restart: always # Garante que o container reinicie automaticamente se parar ou se o Docker reiniciar

  manager:
    # Serviço de gerenciamento visual do banco de dados
    image: adminer # Imagem oficial do Adminer (uma alternativa leve ao phpMyAdmin)
    container_name: <Nome para o container do gerenciador do DB> # Nome do container
    ports:
      - "<a porta host>:8080" # Mapeia a porta do container para a porta escolhida na máquina host
        # Acesse Adminer em http://localhost:<porta escolhida>
       
    restart: always # Reinicia automaticamente caso o container pare
